In [6]:
import numpy as np 
import pandas as pd 
import sklearn
import matplotlib.pyplot as plt 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier

In [7]:
bag=['Aspiring' , 'human', 'resources', 'seeking', 'human', 'resources']

In [18]:
data= pd.read_csv("C:\\Users\\agnes\\Documents\\apziva_ai_residency\\project3\\data\\potential-talents.csv")
words=data.job_title

In [11]:
vect=CountVectorizer()

In [20]:
vect.fit(words)

CountVectorizer()

In [21]:
print('Vocab size:{}'.format(len(vect.vocabulary_)))

Vocab size:200


In [22]:
bag_of_words=vect.transform(words)

In [23]:
print(bag_of_words)

  (0, 0)	1
  (0, 15)	1
  (0, 18)	1
  (0, 23)	1
  (0, 32)	1
  (0, 38)	1
  (0, 46)	1
  (0, 74)	1
  (0, 84)	1
  (0, 103)	1
  (0, 114)	1
  (0, 127)	1
  (0, 146)	1
  (0, 155)	1
  (1, 20)	1
  (1, 59)	2
  (1, 63)	1
  (1, 87)	1
  (1, 101)	1
  (1, 124)	1
  (1, 148)	1
  (1, 180)	1
  (2, 18)	1
  (2, 84)	1
  (2, 146)	1
  :	:
  (99, 163)	1
  (99, 171)	1
  (100, 20)	1
  (100, 71)	1
  (100, 84)	1
  (100, 110)	1
  (100, 155)	1
  (101, 14)	1
  (101, 15)	1
  (101, 20)	1
  (101, 32)	1
  (101, 92)	1
  (101, 187)	1
  (102, 10)	1
  (102, 69)	1
  (102, 166)	1
  (102, 176)	1
  (102, 183)	1
  (102, 190)	1
  (103, 6)	1
  (103, 20)	1
  (103, 51)	1
  (103, 64)	1
  (103, 108)	1
  (103, 127)	1


In [25]:
print('bag of words as an arrzy:\n{}'.format(bag_of_words.toarray()))

bag of words as an arrzy:
[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [27]:
vect.get_feature_names_out()

array(['2019', '2020', '2621', '408', '709', 'about', 'administration',
       'administrative', 'admissions', 'advisory', 'always', 'america',
       'an', 'analyst', 'analytics', 'and', 'army', 'arts', 'aspiring',
       'assistant', 'at', 'atlanta', 'bachelor', 'bauer', 'bayar',
       'beach', 'benefits', 'beneteau', 'biology', 'board', 'brand',
       'buckhead', 'business', 'care', 'celal', 'center', 'chapman',
       'chro', 'college', 'communications', 'community', 'compensation',
       'conflict', 'coordinator', 'create', 'csr', 'cum', 'customer',
       'data', 'delphi', 'development', 'director', 'employment',
       'endemol', 'energetic', 'energy', 'engaging', 'engie', 'engineer',
       'english', 'entry', 'environment', 'environmental', 'epik',
       'excellence', 'executive', 'experienced', 'ey', 'focused', 'for',
       'from', 'generalist', 'gis', 'gphr', 'graduate', 'graduating',
       'groupe', 'guard', 'hardware', 'heil', 'helping', 'houston', 'hr',
       'hris

In [29]:
vect.vocabulary_

{'2019': 0,
 'bauer': 23,
 'college': 38,
 'of': 127,
 'business': 32,
 'graduate': 74,
 'magna': 114,
 'cum': 46,
 'laude': 103,
 'and': 15,
 'aspiring': 18,
 'human': 84,
 'resources': 155,
 'professional': 146,
 'native': 124,
 'english': 59,
 'teacher': 180,
 'at': 20,
 'epik': 63,
 'program': 148,
 'in': 87,
 'korea': 101,
 'people': 140,
 'development': 50,
 'coordinator': 43,
 'ryan': 159,
 'advisory': 9,
 'board': 29,
 'member': 121,
 'celal': 34,
 'bayar': 24,
 'university': 189,
 'specialist': 169,
 'student': 174,
 'humber': 85,
 'generalist': 71,
 'hr': 82,
 'senior': 164,
 'seeking': 163,
 'hris': 83,
 'positions': 144,
 'chapman': 36,
 'svp': 177,
 'chro': 37,
 'marketing': 118,
 'communications': 39,
 'csr': 45,
 'officer': 129,
 'engie': 57,
 'houston': 81,
 'the': 182,
 'woodlands': 197,
 'energy': 55,
 'gphr': 73,
 'sphr': 170,
 'intercontinental': 93,
 'buckhead': 31,
 'atlanta': 21,
 'management': 116,
 'an': 12,
 'internship': 95,
 'opportunities': 132,
 'experienc

In [ ]:
# take out 'an', 'at'
# tdidf 
# get cosine similarity to see 